package org.openapitools.api.impl;

import org.openapitools.api.*;
import org.openapitools.model.Group;
import org.openapitools.model.GroupStub;
import org.openapitools.model.HeadlessUserStub;
import org.openapitools.model.User;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import org.apache.cxf.jaxrs.model.wadl.Description;
import org.apache.cxf.jaxrs.model.wadl.DocTarget;

import org.apache.cxf.jaxrs.ext.multipart.*;

import io.swagger.annotations.Api;

/**
 * Yanis Api
 *
 * <p>No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 */
public class DefaultApiServiceImpl implements DefaultApi {
    public List<Group> unixgroupGet() {
        // TODO: Implement...
        
        return null;
    }
    
    public Group unixgroupNameGet(String name) {
        // TODO: Implement...
        
        return null;
    }
    
    public void unixgroupNameMemberMembernameDelete(String name, String membername) {
        // TODO: Implement...
        
        
    }
    
    public void unixgroupNameMemberMembernamePut(String name, String membername) {
        // TODO: Implement...
        
        
    }
    
    public void unixgroupNamePut(String name, GroupStub groupStub) {
        // TODO: Implement...
        
        
    }
    
    public Group unixgroupPost(GroupStub groupStub) {
        // TODO: Implement...
        
        return null;
    }
    
    public User unixheadlessNameGet(String name) {
        // TODO: Implement...
        
        return null;
    }
    
    /**
     * TODO - address questions about renaming
     *
     * disable/enable a unix headless user
     *
     */
    public void unixheadlessNamePut(String name, HeadlessUserStub headlessUserStub) {
        // TODO: Implement...
        
        
    }
    
    public User unixheadlessPost(HeadlessUserStub headlessUserStub) {
        // TODO: Implement...
        
        return null;
    }
    
    public List<Users> userGet(String type) {
        // TODO: Implement...
                User usr = new User();
        List<User> userList = new ArrayList<>();
        usr.setName("jothip");
        usr.setUid(1234);
        userList.add(usr);
        new User();
        usr.setName("jothi");
        usr.setUid(5678);
        userList.add(usr);

        return userList;
        //return null;
    }
    
    public User userNameGet(String name) {
        // TODO: Implement...
        
        return null;
    }
    
}

